TESTSUITES = ./.__testsuite.sv
UNITTESTS = vgm_reg_map_unit_test.sv 

INCDIR += ../sv
ALLPKGS += ../sv/vgm_uvm_patches.sv

include $(SVUNIT_INSTALL)/bin/questa.mk
include $(SVUNIT_INSTALL)/bin/cfg.mk
